caches:
  - name: go
    cache_key:
      - golang-example-v1
      - { agent: os }
      - { agent: arch }
      - { env: GO_CACHE_VERSION, fallback_limit: true }
      - { checksum: [go.mod, go.sum, "**/*.go"] }
    target_paths:
      - ~/.cache/buildkite-golang-example
