#!/bin/bash

echo "--- :golang: Setting up Golang build environment"

NEW_GOPATH=$(pwd)/tmp/go

mkdir -p $NEW_GOPATH/src/$BUILDKTE_GOLANG_IMPORT_PATH
ln -fs $(pwd) $NEW_GOPATH/src/$BUILDKTE_GOLANG_IMPORT_PATH

export GOPATH=$NEW_GOPATH
echo "New \$GOPATH is set to $NEW_GOPATH"
