#!/bin/bash

set +u

echo "--- :golang: Setting up Golang build environment"

if [[ ! -z "${BUILDKTE_GOLANG_IMPORT_PATH:-}" ]] && [[ "$BUILDKTE_GOLANG_IMPORT_PATH" != "" ]]; then

  NEW_GOPATH=$(pwd)/tmp/go

  mkdir -p $NEW_GOPATH/src/$BUILDKTE_GOLANG_IMPORT_PATH
  ln -fs $(pwd) $NEW_GOPATH/src/$BUILDKTE_GOLANG_IMPORT_PATH

  export GOPATH=$NEW_GOPATH
  echo "New \$GOPATH is set to $NEW_GOPATH"
else
  echo "No \$BUILDKTE_GOLANG_IMPORT_PATH set, skipping..."
fi
