#!/bin/bash

set +u

echo "--- :golang: Updating \$GOPATH"
export GOPATH=$BUILDKITE_BUILD_CHECKOUT_PATH/go
mkdir -p $GOPATH/src
mkdir -p $GOPATH/bin
echo "\$GOPATH is now $GOPATH"

GO_CHECKOUT_PATH="$GOPATH/src/github.com/buildkite/golang-example"
echo "--- :buildkite: Switching checkout path to $GO_CHECKOUT_PATH"
export BUILDKITE_BUILD_CHECKOUT_PATH=$GO_CHECKOUT_PATH
